package com.team1ofus.hermes;

import java.awt.Point;
import java.util.ArrayList;
import java.util.EventObject;
/*
 * Description:    	Holds the list of the different cells(maps), as well as the path that the A* algorithm has generated.
 
Attributes
cells List 
List of cells (maps)
pathMachine AStar 
he path that is generated by the A* algorithm 

Methods

Relationships
AStar               Composition                  Holds an AStar path        
PathUI             

 */
import java.util.List;


public class MapManagement implements IUIManagementInteractionListener  {
	private ArrayList<PathCell> cells;
	AStar pathingSystem;
	MapManagementInteractionEventObject events = new MapManagementInteractionEventObject();
	public MapManagement(ArrayList<PathCell> dummyList) {
		cells = dummyList;
		pathingSystem = new AStar();
	}
	//event getters (used by classes that want to register to the listeners)
	

	
	//event handlers

	public void onCellLoaded(PathCell cell) {
		
	}
	@Override
	public void onPathReady(Point first, Point second) {
		// TODO Auto-generated method stub
		events.pathComplete(pathingSystem.getPath("default", first, "default", first));
		
	}
}